#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 15, 2019 10:01:47 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Open_window_vri_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Open_window (root)
    Open_window_vri_support.init(root, top)
    root.mainloop()

w = None
def create_Open_window(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Open_window (w)
    Open_window_vri_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Open_window():
    global w
    w.destroy()
    w = None

class Open_window:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'

        top.geometry("715x518+514+305")
        top.title("VRI - Virtual Robot Interactions")
        top.configure(background="#2b3f77")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        img = tk.PhotoImage(file="vri_logo.png")
        self.Logo = tk.Label(top, image=img)
        self.Logo.photo = img
        self.Logo.pack()
        self.Logo.place(relx=0.042, rely=0.053, height=140, width=480)
        self.Logo.configure(background="#2b3f77")

        self.whelcome_l = tk.Label(top)
        self.whelcome_l.place(relx=0.042, rely=0.405, height=31, width=443)
        self.whelcome_l.configure(activebackground="#f9f9f9")
        self.whelcome_l.configure(activeforeground="black")
        self.whelcome_l.configure(background="#2b3f77")
        self.whelcome_l.configure(disabledforeground="#a3a3a3")
        self.whelcome_l.configure(font="-family {Showcard Gothic} -size 11 -underline 1")
        self.whelcome_l.configure(foreground="#ffffff")
        self.whelcome_l.configure(highlightbackground="#d9d9d9")
        self.whelcome_l.configure(highlightcolor="black")
        self.whelcome_l.configure(text='''Welcom to VRI - Test your robot in a virtual reality''')

        self.choose_l = tk.Label(top)
        self.choose_l.place(relx=0.084, rely=0.483, height=41, width=216)
        self.choose_l.configure(activebackground="#f9f9f9")
        self.choose_l.configure(activeforeground="black")
        self.choose_l.configure(background="#2b3f77")
        self.choose_l.configure(disabledforeground="#a3a3a3")
        self.choose_l.configure(font="-family {Guttman Miryam} -size 11 -weight bold -underline 1")
        self.choose_l.configure(foreground="#ffffff")
        self.choose_l.configure(highlightbackground="#d9d9d9")
        self.choose_l.configure(highlightcolor="black")
        self.choose_l.configure(text='''Please choose your action:''')

        self.test_b = tk.Button(top)
        self.test_b.place(relx=0.154, rely=0.637, height=64, width=264)
        self.test_b.configure(activebackground="#d9d9d9")
        self.test_b.configure(activeforeground="#000000")
        self.test_b.configure(background="#8bd8bd")
        self.test_b.configure(disabledforeground="#a3a3a3")
        self.test_b.configure(font="-family {Tahoma} -size 13")
        self.test_b.configure(foreground="#000000")
        self.test_b.configure(highlightbackground="#d9d9d9")
        self.test_b.configure(highlightcolor="black")
        self.test_b.configure(pady="0")
        self.test_b.configure(text='''Start testing''')
        self.test_b.bind('<Button-1>',lambda e:Open_window_vri_support.start_test(top))

        self.xml_b = tk.Button(top)
        self.xml_b.place(relx=0.154, rely=0.792, height=64, width=267)
        self.xml_b.configure(activebackground="#d9d9d9")
        self.xml_b.configure(activeforeground="#000000")
        self.xml_b.configure(background="#8bd8bd")
        self.xml_b.configure(disabledforeground="#a3a3a3")
        self.xml_b.configure(font="-family {Tahoma} -size 11")
        self.xml_b.configure(foreground="#000000")
        self.xml_b.configure(highlightbackground="#d9d9d9")
        self.xml_b.configure(highlightcolor="black")
        self.xml_b.configure(pady="0")
        self.xml_b.configure(text='''XML instructions,
tutorial adn examples''')
        self.xml_b.bind('<Button-1>',lambda e:Open_window_vri_support.xxx(e))

        self.designer_b = tk.Button(top)
        self.designer_b.place(relx=0.559, rely=0.637, height=64, width=267)
        self.designer_b.configure(activebackground="#d9d9d9")
        self.designer_b.configure(activeforeground="#000000")
        self.designer_b.configure(background="#8bd8bd")
        self.designer_b.configure(disabledforeground="#a3a3a3")
        self.designer_b.configure(font="-family {Tahoma} -size 11")
        self.designer_b.configure(foreground="#000000")
        self.designer_b.configure(highlightbackground="#d9d9d9")
        self.designer_b.configure(highlightcolor="black")
        self.designer_b.configure(pady="0")
        self.designer_b.configure(text='''Designer''')
        self.designer_b.bind('<Button-1>',lambda e:Open_window_vri_support.xxx(e))

        self.about_b = tk.Button(top)
        self.about_b.place(relx=0.559, rely=0.792, height=64, width=264)
        self.about_b.configure(activebackground="#d9d9d9")
        self.about_b.configure(activeforeground="#000000")
        self.about_b.configure(background="#8bd8bd")
        self.about_b.configure(disabledforeground="#a3a3a3")
        self.about_b.configure(font="-family {Tahoma} -size 13")
        self.about_b.configure(foreground="#000000")
        self.about_b.configure(highlightbackground="#d9d9d9")
        self.about_b.configure(highlightcolor="black")
        self.about_b.configure(pady="0")
        self.about_b.configure(text='''About the program''')
        self.about_b.bind('<Button-1>',lambda e:Open_window_vri_support.xxx(e))

if __name__ == '__main__':
    vp_start_gui()





