#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 15, 2019 10:01:52 PM +0300  platform: Windows NT

import sys
import temp_screen
import Environment
import pre_testing
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def start_test(root):
    destroy_window()
    print('Opening Get Data Screen')
    pre_testing.vp_start_gui()

def xxx(root):
    print('Open_window_vri_support.xxx')
    screen = temp_screen.create_env_screen(root)
    screen[1].destroy_window()
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import Open_window_vri
    Open_window_vri.vp_start_gui()




