#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 15, 2019 10:01:48 PM +0300  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#2b3f77} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 715x518+514+305
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "VRI - Virtual Robot Interactions"
    vTcl:DefineAlias "$top" "Open_window" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#2b3f77} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text logo 
    vTcl:DefineAlias "$top.lab43" "Logo" vTcl:WidgetProc "Open_window" 1
    vTcl:copy_lock $top.lab43
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#2b3f77} -disabledforeground {#a3a3a3} \
        -font {-family {Showcard Gothic} -size 11 -underline 1} \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black \
        -text {Welcom to VRI - Test your robot in a virtual reality} 
    vTcl:DefineAlias "$top.lab44" "whelcome_l" vTcl:WidgetProc "Open_window" 1
    label $top.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#2b3f77} -disabledforeground {#a3a3a3} \
        -font {-family {Guttman Miryam} -size 11 -weight bold -underline 1} \
        -foreground {#ffffff} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Please choose your action:} 
    vTcl:DefineAlias "$top.lab46" "choose_l" vTcl:WidgetProc "Open_window" 1
    button $top.but47 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#8bd8bd} -disabledforeground {#a3a3a3} \
        -font {-family {Tahoma} -size 13} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Start testing} 
    vTcl:DefineAlias "$top.but47" "test_b" vTcl:WidgetProc "Open_window" 1
    bind $top.but47 <Button-1> {
        lambda e: xxx(e)
    }
    button $top.but48 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#8bd8bd} -disabledforeground {#a3a3a3} \
        -font {-family {Tahoma} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {XML instructions,
tutorial adn examples } 
    vTcl:DefineAlias "$top.but48" "xml_b" vTcl:WidgetProc "Open_window" 1
    bind $top.but48 <Button-1> {
        lambda e: xxx(e)
    }
    button $top.but50 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#8bd8bd} -disabledforeground {#a3a3a3} \
        -font {-family {Tahoma} -size 11} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Designer 
    vTcl:DefineAlias "$top.but50" "designer_b" vTcl:WidgetProc "Open_window" 1
    bind $top.but50 <Button-1> {
        lambda e: xxx(e)
    }
    button $top.but68 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#8bd8bd} -disabledforeground {#a3a3a3} \
        -font {-family {Tahoma} -size 13} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {About the program} 
    vTcl:DefineAlias "$top.but68" "about_b" vTcl:WidgetProc "Open_window" 1
    bind $top.but68 <Button-1> {
        lambda e: xxx(e)
    }
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 30 -y 30 -width 480 -relwidth 0 -height 140 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 30 -y 210 -width 443 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 60 -y 250 -width 216 -relwidth 0 -height 41 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 110 -y 330 -width 264 -relwidth 0 -height 64 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but48 \
        -in $top -x 110 -y 410 -width 267 -relwidth 0 -height 64 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 400 -y 330 -width 267 -relwidth 0 -height 64 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but68 \
        -in $top -x 400 -y 410 -width 264 -height 64 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

