#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Jun 12, 2019 05:50:49 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from GUI import About_The_Program_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = about_the_program (root)
    About_The_Program_support.init(root, top)
    root.mainloop()

w = None
def create_about_the_program(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = about_the_program (w)
    About_The_Program_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_about_the_program():
    global w
    w.destroy()
    w = None

class about_the_program:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'

        top.geometry("600x330+619+272")
        top.title("VRI - About")
        top.configure(background="#2b3f77")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.067, rely=0.091, height=31, width=254)
        self.Label1.configure(background="#2b3f77")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI Light} -size 15 -weight bold -underline 1")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''About the program:''')
        self.Label1.configure(width=254)

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.050, rely=0.303, height=31, width=700)
        self.Label2.configure(background="#2b3f77")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font="-family {Segoe UI} -size 10")
        self.Label2.configure(foreground="#ffffff")
        txt = 'התוכנה היא סימולטור בדיקה אשר מטרתה לאפשר סביבה ווירטואלי'
        txt += '\n'
        txt += 'שבה יהיה ניתן לבחון את ביצועי ברובוט ללא חשש לפגיעה בו או בסביבה שלידו'
        self.Label2.configure(text=txt)
        self.Label2.configure(width=257)

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.05, rely=0.788, height=44, width=127)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Button''')
        self.Button1.configure(width=127)
        self.Button1.configure(text='Back')
        self.Button1.bind('<Button-1>',lambda e:About_The_Program_support.back())

if __name__ == '__main__':
    vp_start_gui()





