#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.21
#  in conjunction with Tcl version 8.6
#    Jun 02, 2019 03:14:54 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

from GUI import Designer_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Vri_Designer (root)
    Designer_support.init(root, top)
    root.mainloop()

w = None
def create_Vri_Designer(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Vri_Designer (w)
    Designer_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Vri_Designer():
    global w
    w.destroy()
    w = None

class Vri_Designer:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 12"
        font9 = "-family {Segoe UI} -size 11"

        top.geometry("1348x1000+101+1")
        top.title("VRI - Desinger")
        top.configure(background="#d8d4b3")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.canvas = tk.Canvas(top)
        self.canvas.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=0.89)
        self.canvas.configure(background="#ffffff")
        self.canvas.configure(borderwidth="2")
        self.canvas.configure(insertbackground="black")
        self.canvas.configure(relief='ridge')
        self.canvas.configure(selectbackground="#c4c4c4")
        self.canvas.configure(selectforeground="black")
        self.canvas.configure(width=323)

        self.canvas.create_line()


        self.save_b = tk.Button(top)
        self.save_b.place(relx=0.89, rely=0.03, height=44, width=147)
        self.save_b.configure(activebackground="#ececec")
        self.save_b.configure(activeforeground="#000000")
        self.save_b.configure(background="#d9d9d9")
        self.save_b.configure(disabledforeground="#a3a3a3")
        self.save_b.configure(font=font10)
        self.save_b.configure(foreground="#000000")
        self.save_b.configure(highlightbackground="#d9d9d9")
        self.save_b.configure(highlightcolor="black")
        self.save_b.configure(pady="0")
        self.save_b.configure(text='''Save''')
        self.save_b.configure(width=147)

        self.exit_b = tk.Button(top)
        self.exit_b.place(relx=0.89, rely=0.11, height=44, width=147)
        self.exit_b.configure(activebackground="#ececec")
        self.exit_b.configure(activeforeground="#000000")
        self.exit_b.configure(background="#d9d9d9")
        self.exit_b.configure(disabledforeground="#a3a3a3")
        self.exit_b.configure(font=font9)
        self.exit_b.configure(foreground="#000000")
        self.exit_b.configure(highlightbackground="#d9d9d9")
        self.exit_b.configure(highlightcolor="black")
        self.exit_b.configure(pady="0")
        self.exit_b.configure(text='''Exit''')
        self.exit_b.configure(width=147)

if __name__ == '__main__':
    vp_start_gui()





