#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    Jun 10, 2019 04:34:24 PM +0300  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import Designer_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = designer (root)
    Designer_support.init(root, top)
    root.mainloop()

w = None
def create_designer(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = designer (w)
    Designer_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_designer():
    global w
    w.destroy()
    w = None

class designer:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#d9d9d9' # X11 color: 'gray85'
        font9 = "-family {Segoe UI} -size 9"

        top.geometry("1200x1000+190+0")
        top.title("VRI - Designer")
        top.configure(background="#d8c7a0")

        self.menubar = tk.Menu(top, font=('Segoe UI', 9, ), bg=_bgcolor
                ,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.canvas = tk.Canvas(top)
        self.canvas.place(relx=0.0, rely=0.0, relheight=1.0, relwidth=0.833)
        self.canvas.configure(background="#ffffff")
        self.canvas.configure(borderwidth="2")
        self.canvas.configure(insertbackground="black")
        self.canvas.configure(relief="ridge")
        self.canvas.configure(selectbackground="#c4c4c4")
        self.canvas.configure(selectforeground="black")
        self.canvas.configure(width=125)

        self.save_b = tk.Button(top)
        self.save_b.place(relx=0.833, rely=0.84, height=54, width=197)
        self.save_b.configure(activebackground="#d9d9d9")
        self.save_b.configure(activeforeground="#000000")
        self.save_b.configure(background="#d9d9d9")
        self.save_b.configure(disabledforeground="#a3a3a3")
        self.save_b.configure(foreground="#000000")
        self.save_b.configure(highlightbackground="#d9d9d9")
        self.save_b.configure(highlightcolor="black")
        self.save_b.configure(pady="0")
        self.save_b.configure(text='''Save''')
        self.save_b.configure(width=197)
        self.save_b.bind('<Button-1>',lambda e:Designer_support.xxx(e))

        self.exit_b = tk.Button(top)
        self.exit_b.place(relx=0.833, rely=0.91, height=54, width=197)
        self.exit_b.configure(activebackground="#d9d9d9")
        self.exit_b.configure(activeforeground="#000000")
        self.exit_b.configure(background="#d9d9d9")
        self.exit_b.configure(disabledforeground="#a3a3a3")
        self.exit_b.configure(foreground="#000000")
        self.exit_b.configure(highlightbackground="#d9d9d9")
        self.exit_b.configure(highlightcolor="black")
        self.exit_b.configure(pady="0")
        self.exit_b.configure(text='''Exit''')
        self.exit_b.bind('<Button-1>',lambda e:Designer_support.xxx(e))

        self.wall_b = tk.Button(top)
        self.wall_b.place(relx=0.833, rely=0.05, height=54, width=197)
        self.wall_b.configure(activebackground="#d9d9d9")
        self.wall_b.configure(activeforeground="#000000")
        self.wall_b.configure(background="#d9d9d9")
        self.wall_b.configure(disabledforeground="#a3a3a3")
        self.wall_b.configure(foreground="#000000")
        self.wall_b.configure(highlightbackground="#d9d9d9")
        self.wall_b.configure(highlightcolor="black")
        self.wall_b.configure(pady="0")
        self.wall_b.configure(text='''Wall''')
        self.wall_b.bind('<Button-1>',lambda e:Designer_support.xxx(e))

        self.robot_b = tk.Button(top)
        self.robot_b.place(relx=0.833, rely=0.13, height=54, width=197)
        self.robot_b.configure(activebackground="#d9d9d9")
        self.robot_b.configure(activeforeground="#000000")
        self.robot_b.configure(background="#d9d9d9")
        self.robot_b.configure(disabledforeground="#a3a3a3")
        self.robot_b.configure(foreground="#000000")
        self.robot_b.configure(highlightbackground="#d9d9d9")
        self.robot_b.configure(highlightcolor="black")
        self.robot_b.configure(pady="0")
        self.robot_b.configure(text='''Robot''')
        self.robot_b.bind('<Button-1>',lambda e:Designer_support.xxx(e))

        self.sensor_b = tk.Button(top)
        self.sensor_b.place(relx=0.833, rely=0.21, height=54, width=197)
        self.sensor_b.configure(activebackground="#d9d9d9")
        self.sensor_b.configure(activeforeground="#000000")
        self.sensor_b.configure(background="#d9d9d9")
        self.sensor_b.configure(disabledforeground="#a3a3a3")
        self.sensor_b.configure(foreground="#000000")
        self.sensor_b.configure(highlightbackground="#d9d9d9")
        self.sensor_b.configure(highlightcolor="black")
        self.sensor_b.configure(pady="0")
        self.sensor_b.configure(text='''Sensor''')
        self.sensor_b.bind('<Button-1>',lambda e:Designer_support.xxx(e))


if __name__ == '__main__':
    vp_start_gui()





