#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 15, 2019 10:01:52 PM +0300  platform: Windows NT

"""
Author: Yotam Levit
Project - VRI
"""

import sys
from GUI import pre_testing
from GUI import Designer
from GUI import About_The_Program
from GUI import XML

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def xml():
    """
    open the xml screen
    """
    destroy_window()
    print('open xml inst')
    XML.vp_start_gui()


def about():
    """
    open the about screen
    """
    destroy_window()
    print('opening About screen')
    About_The_Program.vp_start_gui()

def start_test():
    """
    open get data screen
    """
    destroy_window()
    print('Opening Get Data Screen')
    pre_testing.vp_start_gui()

def designer():
    """
    open the designer
    """
    destroy_window()
    print('Opening Designer Window')
    Designer.vp_start_gui()



def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    from GUI import Open_window_vri
    Open_window_vri.vp_start_gui()




