#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 16, 2019 06:36:12 PM +0300  platform: Windows NT

import sys
from Objects.Environment import Environment
from GUI import Simulator, Open_window_vri
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def continue_pressed(env_file, file_logic, path_log):
    destroy_window()
    print('Reading Data')
    env = Environment.environment_from_file(env_file)
    print('Data read')
    print('Start testing')
    Simulator.vp_start_gui(env, file_logic, path_log)


def back_pressed():
    destroy_window()
    print('Opening Open Screen')
    Open_window_vri.vp_start_gui()
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    from GUI import pre_testing
    pre_testing.vp_start_gui()




