#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 16, 2019 07:59:33 PM +0300  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 11 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font11
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist {_TopLevel _vTclBalloon}
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#2b3f77} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 354x154+623+442
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "VRI - Virtual Robot Interactions"
    vTcl:DefineAlias "$top" "Get_Sim_Data" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#2b3f77} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 11} -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Environment File:} 
    vTcl:DefineAlias "$top.lab43" "Label_file" vTcl:WidgetProc "Get_Sim_Data" 1
    entry $top.ent64 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 10} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent64" "Entry_file_name" vTcl:WidgetProc "Get_Sim_Data" 1
    ttk::separator $top.tSe66
    vTcl:DefineAlias "$top.tSe66" "TSeparator1" vTcl:WidgetProc "Get_Sim_Data" 1
    button $top.but68 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text Back 
    vTcl:DefineAlias "$top.but68" "Back" vTcl:WidgetProc "Get_Sim_Data" 1
    bind $top.but68 <Button-1> {
        lambda e: xxx(e)
    }
    button $top.but69 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font TkDefaultFont -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -pady 0 \
        -text {Read Environment
 and start testing} 
    vTcl:DefineAlias "$top.but69" "Continue" vTcl:WidgetProc "Get_Sim_Data" 1
    bind $top.but69 <Button-1> {
        lambda e: xxx(e)
    }
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#2b3f77} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 11} -foreground {#ffffff} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Action File:} 
    vTcl:DefineAlias "$top.lab44" "action_lable" vTcl:WidgetProc "Get_Sim_Data" 1
    entry $top.ent45 \
        -background white -disabledforeground {#a3a3a3} \
        -font {-family {Courier New} -size 10} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$top.ent45" "action_file" vTcl:WidgetProc "Get_Sim_Data" 1
    label $top.lab50 \
        -background {#2b3f77} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 11 -weight bold} \
        -foreground {#ff0000} 
    vTcl:DefineAlias "$top.lab50" "error" vTcl:WidgetProc "Get_Sim_Data" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 40 -y 20 -width 121 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent64 \
        -in $top -x 170 -y 20 -anchor nw -bordermode ignore 
    place $top.tSe66 \
        -in $top -x 40 -y 50 -width 300 -anchor nw -bordermode inside 
    place $top.but68 \
        -in $top -x 50 -y 100 -width 66 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but69 \
        -in $top -x 190 -y 100 -width 149 -relwidth 0 -height 44 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 20 -y 60 -width 121 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.ent45 \
        -in $top -x 170 -y 60 -width 164 -relwidth 0 -height 20 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 40 -y 0 -width 303 -relwidth 0 -height 26 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

