#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#    May 17, 2019 02:52:22 PM +0300  platform: Windows NT

from GUI import Open_window_vri
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def set_Tk_var():
    global speed_value
    speed_value = tk.DoubleVar()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

def exit():
    destroy_window()
    print('opening Open Screen')
    Open_window_vri.vp_start_gui()

def move(lap):
    if lap < 160:
        return 's'
    elif 160 < lap <= 250:
        return 'd'
    #if 180 <= lap <2000:
     #   return 'w'
    #if 200 <= lap < 3000:
     #   return 's'
    return None

if __name__ == '__main__':
    from GUI import Simulator
    Simulator.vp_start_gui()




